/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 08 16:45:52 GMT 2020
 */
package temp.replacement_repo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import temp.replacement_repo.CustomObject;
import temp.replacement_repo.OriginalClass;
import xml.XMLParser;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class TEST_COLUMBIA_SABER_OriginalClass extends OriginalClass_ESTest_scaffolding {

    @Test(timeout = 4000)
    public static void test0() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        Integer integer0 = Integer.valueOf(209);
        linkedList0.add(integer0);
        CustomObject customObject0 = new CustomObject();
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(linkedList0, customObject0);
        assertEquals("0_2", string0);
    }

    @Test(timeout = 4000)
    public static void test1() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        int int0 = originalClass0.originalMethod(linkedList0, 0);
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public static void test2() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        int int0 = originalClass0.originalMethod(linkedList0, 472);
        assertEquals(472, int0);
    }

    @Test(timeout = 4000)
    public static void test3() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        linkedList0.offerFirst((Integer) null);
        // Undeclared exception!
        try {
            originalClass0.originalMethod(linkedList0, (-2774));
            fail("Expecting exception: NullPointerException");
        } catch (NullPointerException e) {
            // 
            // no message in exception (getMessage() returned null)
            // 
            verifyException("temp.replacement_repo.OriginalClass", e);
        }
    }

    @Test(timeout = 4000)
    public static void test4() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        // Undeclared exception!
        try {
            originalClass0.objectMethod(linkedList0, (CustomObject) null);
            fail("Expecting exception: NullPointerException");
        } catch (NullPointerException e) {
            // 
            // no message in exception (getMessage() returned null)
            // 
            verifyException("temp.replacement_repo.OriginalClass", e);
        }
    }

    @Test(timeout = 4000)
    public static void test5() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(linkedList0, customObject0);
        assertEquals("list size greater than 2", string0);
    }

    @Test(timeout = 4000)
    public static void test6() throws Throwable {
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        int int0 = originalClass0.originalMethod(linkedList0, (-22));
        assertEquals((-44), int0);
    }

    public static void main(String[] args) throws Throwable {
        test5_SABER_1696581258_1583698251030_objectMethod_1();
        test5_SABER_1239656641_1583698250957_objectMethod_1();
        test5_SABER_1540290190_1583698250972_objectMethod_1();
        test5_SABER_981315617_1583698251011_objectMethod_1();
        test5_SABER_269995176_1583698250930_objectMethod_1();
        test5_SABER_792806907_1583698250963_objectMethod_1();
        test5_SABER_1521288167_1583698250937_objectMethod_1();
        test5_SABER_1637089564_1583698250943_objectMethod_1();
        test5_SABER_1898575367_1583698250979_objectMethod_1();
        test5_SABER_359160402_1583698251000_objectMethod_1();
        test5_SABER_1101112095_1583698250951_objectMethod_1();
        test5_SABER_1793986052_1583698250992_objectMethod_1();
        test5_SABER_71062292_1583698250986_objectMethod_1();
        test1_SABER_635115106_1583698251006_originalMethod_1();
        test1_SABER_1328037091_1583698251024_originalMethod_1();
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1696581258_1583698251030_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1696581258_1583698251030_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1239656641_1583698250957_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1239656641_1583698250957_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1540290190_1583698250972_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1540290190_1583698250972_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_981315617_1583698251011_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_981315617_1583698251011_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_269995176_1583698250930_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_269995176_1583698250930_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_792806907_1583698250963_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_792806907_1583698250963_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1521288167_1583698250937_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1521288167_1583698250937_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1637089564_1583698250943_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1637089564_1583698250943_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1898575367_1583698250979_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1898575367_1583698250979_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_359160402_1583698251000_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_359160402_1583698251000_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1101112095_1583698250951_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1101112095_1583698250951_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_1793986052_1583698250992_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1793986052_1583698250992_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test5_SABER_71062292_1583698250986_objectMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_71062292_1583698250986_objectMethod_1.xml");
        java.util.LinkedList newInput0 = (java.util.LinkedList) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        CustomObject customObject0 = new CustomObject();
        Integer integer0 = new Integer((-22));
        linkedList0.add(integer0);
        linkedList0.push(integer0);
        linkedList0.add(integer0);
        String string0 = originalClass0.objectMethod(newInput0, customObject0);
    }

    @Test(timeout = 4000)
    public static void test1_SABER_635115106_1583698251006_originalMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_635115106_1583698251006_originalMethod_1.xml");
        java.lang.Integer newInput0 = (java.lang.Integer) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        int int0 = originalClass0.originalMethod(linkedList0, newInput0);
    }

    @Test(timeout = 4000)
    public static void test1_SABER_1328037091_1583698251024_originalMethod_1() throws Throwable {
        XMLParser xmlParser = new XMLParser("/Users/adityasridhar/Documents/COLUMBIA/SABER/source_codebase/xml_file_dump/TEST_COLUMBIA_SABER_xmlFileDump_SABER_1328037091_1583698251024_originalMethod_1.xml");
        java.lang.Integer newInput0 = (java.lang.Integer) xmlParser.getNewInputByIndex(0);
        OriginalClass originalClass0 = new OriginalClass();
        LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
        int int0 = originalClass0.originalMethod(linkedList0, newInput0);
    }
}

